name: main_action
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install cpplint
    - run: cpplint --extensions=hpp,cpp,h,c,ino --recursive .
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: 'update'
  build:
    runs-on: ubuntu-latest
    env:
        SKETCH_NAME: ESP_jQuery_Mobile_Interface
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - run: pip install esptool
      - run: sh ./ESP_Action_Build_Scripts/build_data.sh ${{env.SKETCH_NAME}}
      - run: sh ./ESP_Action_Build_Scripts/build_sketch.sh ESP8266
      - run: sh ./ESP_Action_Build_Scripts/build_sketch.sh ESP32
#      - run: sh ./ESP_Action_Build_Scripts/save_raw_data.sh
#      - uses: actions/upload-artifact@v2
#        with:
#          name: store-raw-build-data
#          path: ./Artifacts/raw_build_data.zip
      - run: sh ./ESP_Action_Build_Scripts/create_eef_package.sh ${{env.SKETCH_NAME}}
      - uses: actions/upload-artifact@v2
        with:
          name: store-eef-package
          path: ./Artifacts/${{env.SKETCH_NAME}}.eep
  
          
